server:
  port: 8080

#spring:
  #cloud:
    #gateway:
      #routes:
      #- id: one
        #uri: http://localhost:8081
        #predicates:
        #- Path=/serviceOne/**
      #- id: two
        #uri: http://localhost:8082
        #predicates:
        #- Path=/serviceTwo/**



